repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: "^(src/.*\\.py|tests/.*\\.py|.*\\.yml|.*\\.yaml)$"
      - id: end-of-file-fixer
        files: "^(src/.*\\.py|tests/.*\\.py|.*\\.yml|.*\\.yaml)$"
      - id: check-yaml
        files: "^(.*\\.yml|.*\\.yaml)$"
        args: ['--unsafe']
      - id: check-added-large-files
        files: "^(src/.*\\.py|tests/.*\\.py|.*\\.yml|.*\\.yaml)$"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix, --exit-zero]
        files: "^(src|tests)/.*\\.py$"
      - id: ruff-format
        files: "^(src|tests)/.*\\.py$"
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        files: ".*"
